# Generated by Django 2.1.7 on 2019-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=10)),
                ('contact_number', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
