# Generated by Django 2.1.7 on 2019-04-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='UserDetails',
        ),
    ]
