# Generated by Django 2.1.7 on 2019-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationModule', '0002_auto_20190405_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=10)),
                ('contact_number', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
