# Generated by Django 2.1.7 on 2019-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationModule', '0004_auto_20190405_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
