# Generated by Django 2.1.7 on 2019-04-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTicketDetails',
            fields=[
                ('PNRno', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=5)),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationId1', models.CharField(max_length=5)),
                ('stationId2', models.CharField(max_length=5)),
                ('coachCC', models.IntegerField()),
                ('coach2S', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoachDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachCC', models.IntegerField()),
                ('coach2S', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassengerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('statinName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.CharField(max_length=5)),
                ('departure', models.CharField(max_length=5)),
                ('stationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTicket.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TrainBooked',
            fields=[
                ('date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('availableCC', models.IntegerField()),
                ('available2S', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainDetails',
            fields=[
                ('trainNo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('trainName', models.CharField(max_length=30)),
                ('trainType', models.CharField(max_length=10)),
                ('noOfCCCoach', models.IntegerField()),
                ('noOf2SCoach', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trainbooked',
            name='trainNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTicket.TrainDetails'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='trainNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTicket.TrainDetails'),
        ),
        migrations.AddField(
            model_name='passengerdetails',
            name='PNRno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTicket.TrainDetails'),
        ),
        migrations.AddField(
            model_name='bookedticketdetails',
            name='trainNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTicket.TrainDetails'),
        ),
    ]
