# Generated by Django 2.1.7 on 2019-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetails',
            name='coachNo',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengerdetails',
            name='seatNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
