# Generated by Django 2.1.7 on 2019-04-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0002_auto_20190406_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdetails',
            name='PNRno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTicket.BookedTicketDetails'),
        ),
    ]
