# Generated by Django 2.1.7 on 2019-04-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0003_auto_20190407_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticketdetails',
            name='doj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BookTicket.TrainBooked'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedticketdetails',
            name='username',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
